services:
  db-dev:
    image: "postgres:16.3-alpine3.20"
    environment:
      POSTGRES_DB: "todoapp"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "15432:5432"
    profiles: [ "dev" ]
    volumes:
      - dev-data:/var/lib/postgresql/data

  db-test:
    image: "postgres:16.3-alpine3.20"
    environment:
      POSTGRES_DB: "test-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "15433:5432"
    profiles: [ "test" ]

  smtp:
    image: "axllent/mailpit"
    command: [ "--enable-spamassassin", "postmark" ]
    ports:
      - "8025:8025"
      - "1025:1025"
    profiles: [ "test", "dev" ]

volumes:
  dev-data: