logging:
  level:
    org:
      springframework:
        web: "TRACE"

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expiration: ${JWT_EXPIRATION}

spring:
  application:
    name: "todoapp"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: "classpath:/db/changelog/root-changelog.yaml"
  sql:
    init:
      mode: "always"

