logging:
  level:
    org:
      springframework:
        web: "WARN"
        security:
          web:
            FilterChainProxy: "WARN"

spring:
  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: false