admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
logging:
  level:
    org:
      springframework:
        boot: "DEBUG"
        web: "DEBUG"
        security:
          web:
            FilterChainProxy: "DEBUG"
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  address: "0.0.0.0"
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: "Todoapp"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: "UTC"
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: "UTC"
    show-sql: true
  liquibase:
    change-log: "classpath:/db/changelog/root-changelog.yaml"
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: "smtp"
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  sql:
    init:
      mode: "never"
client:
  uri:
    unlock-user: ${CLIENT_URI_UNLOCK_USER}