logging:
  level:
    org:
      springframework:
        web: "TRACE"
        security:
          web:
            FilterChainProxy: "DEBUG"

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expires-in: ${JWT_EXPIRATION}
  refresh-expires-in: ${REFRESH_JWT_EXPIRATION}

spring:
  application:
    name: "todoapp"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    time-zone: "UTC"
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: "UTC"
    show-sql: true
  liquibase:
    change-log: "classpath:/db/changelog/root-changelog.yaml"
  sql:
    init:
      mode: "always"

