client:
  uri:
    unlock-user: "http://localhost:3000/unlock-user"

jwt:
  secret: "secret"

logging:
  level:
    org:
      springframework:
        boot: "DEBUG"
        web: "DEBUG"
        security:
          web:
            FilterChainProxy: "WARN"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
    beans:
      enabled: true
  info:
    env:
      enabled: true

server:
  address: "localhost"
  port: 8080
  ssl:
    enabled: false

spring:
  application:
    name: "Todoapp"
  jackson:
    time-zone: "UTC"
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: "UTC"
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: "classpath:/db/changelog/root-changelog.yaml"
  mail:
    host: "localhost"
    port: 1025
    username: "support@example.com"
    properties:
      mail:
        transport:
          protocol: "smtp"
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  profiles:
    active: "dev"
  sql:
    init:
      mode: "never"

tasks:
  weekly: "0 0 0 */7 * ?"