logging:
  level:
    org:
      springframework:
        boot: "INFO"
        web: "INFO"
        security:
          web:
            FilterChainProxy: "INFO"

spring:
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: false
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
