logging:
  level:
    org:
      springframework:
        boot: "WARN"
        web: "WARN"
        security:
          web:
            FilterChainProxy: "WARN"

spring:
  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: false
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
