admin:
  email: "admin@example.com"
  password: "secretPassword1234!?"
jwt:
  secret: "ultraSecret"
logging:
  level:
    org:
      springframework:
        boot: "DEBUG"
        web: "DEBUG"
        security:
          web:
            FilterChainProxy: "DEBUG"
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  address: "0.0.0.0"
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: "Todoapp"
  docker:
    compose:
      skip:
        in-tests: false
      lifecycle-management: start_only
      enabled: true
  jackson:
    time-zone: "UTC"
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: "UTC"
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: "classpath:/db/changelog/root-changelog.yaml"
  mail:
    host: "localhost"
    port: 1025
    username: "no-reply@example.com"
    properties:
      mail:
        transport:
          protocol: "smtp"
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  sql:
    init:
      mode: "never"
client:
  uri:
    unlock-user: "http://localhost:3000/unlock-user"