logging:
  level:
    org:
      springframework:
        web: "TRACE"

server:
  ssl:
    key-store: "classpath:certificate.p12"
    key-store-type: "PKCS12"
    key-store-password: "Vftcg7af2023!?"

spring:
  application:
    name: "todoapp"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
  liquibase:
    change-log: "classpath:/db/changelog/root-changelog.yaml"

